// Generated by scripts/agent/generate.mjs. Do not edit.
export type AnnotationPlan = {
"version": 1;
"framework": "vanilla" | "react" | "vue" | "svelte" | "angular";
"intent": string;
"annotations": Array<{
"id": string;
"primitive": "circle";
"targets": [{
"strategy": "ref" | "id" | "data-attribute" | "source" | "stet-attribute" | "css";
"file": string;
"locator": string;
"description": string;
"rationale"?: string;
}];
"options"?: {
"seed"?: number;
"roughness"?: number;
"boil"?: number;
"stroke"?: string;
"fill"?: string;
"width"?: number;
"resketchOnHover"?: boolean;
"padding"?: number;
"description"?: string;
};
} | {
"id": string;
"primitive": "underline";
"targets": [{
"strategy": "ref" | "id" | "data-attribute" | "source" | "stet-attribute" | "css";
"file": string;
"locator": string;
"description": string;
"rationale"?: string;
}];
"options"?: {
"seed"?: number;
"roughness"?: number;
"boil"?: number;
"stroke"?: string;
"fill"?: string;
"width"?: number;
"resketchOnHover"?: boolean;
"padding"?: number;
"description"?: string;
};
} | {
"id": string;
"primitive": "highlight";
"targets": [{
"strategy": "ref" | "id" | "data-attribute" | "source" | "stet-attribute" | "css";
"file": string;
"locator": string;
"description": string;
"rationale"?: string;
}];
"options"?: {
"seed"?: number;
"roughness"?: number;
"boil"?: number;
"stroke"?: string;
"fill"?: string;
"width"?: number;
"resketchOnHover"?: boolean;
"padding"?: number;
"description"?: string;
};
} | {
"id": string;
"primitive": "arrow";
"targets": [{
"strategy": "ref" | "id" | "data-attribute" | "source" | "stet-attribute" | "css";
"file": string;
"locator": string;
"description": string;
"rationale"?: string;
}, {
"strategy": "ref" | "id" | "data-attribute" | "source" | "stet-attribute" | "css";
"file": string;
"locator": string;
"description": string;
"rationale"?: string;
}];
"options"?: {
"label"?: string;
"curvature"?: number;
"labelOffsetX"?: number;
"labelOffsetY"?: number;
"seed"?: number;
"roughness"?: number;
"boil"?: number;
"stroke"?: string;
"fill"?: string;
"width"?: number;
"resketchOnHover"?: boolean;
"padding"?: number;
"description"?: string;
};
} | {
"id": string;
"primitive": "sticky";
"targets": [{
"strategy": "ref" | "id" | "data-attribute" | "source" | "stet-attribute" | "css";
"file": string;
"locator": string;
"description": string;
"rationale"?: string;
}];
"options": {
"text": string;
"side"?: "auto" | "top" | "right" | "bottom" | "left";
"offsetX"?: number;
"offsetY"?: number;
"seed"?: number;
"roughness"?: number;
"boil"?: number;
"stroke"?: string;
"fill"?: string;
"width"?: number;
"resketchOnHover"?: boolean;
"padding"?: number;
"description"?: string;
};
} | {
"id": string;
"primitive": "mark";
"targets": [{
"strategy": "ref" | "id" | "data-attribute" | "source" | "stet-attribute" | "css";
"file": string;
"locator": string;
"description": string;
"rationale"?: string;
}];
"options"?: {
"seed"?: number;
"roughness"?: number;
"boil"?: number;
"stroke"?: string;
"fill"?: string;
"width"?: number;
"resketchOnHover"?: boolean;
"padding"?: number;
"description"?: string;
};
"kind": "right" | "wrong";
}>;
};
